# Generated by Django 5.0.6 on 2025-05-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postengagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostEngagement',
        ),
    ]
