# Generated by Django 5.0.6 on 2025-05-21 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=50, unique=True)),
                ('email', models.CharField(db_column='email', max_length=100, unique=True)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255)),
                ('full_name', models.CharField(blank=True, db_column='full_name', max_length=100, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
