# Generated by Django 5.0.6 on 2025-05-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Messages',
                'managed': False,
            },
        ),
    ]
