# Generated by Django 5.0.6 on 2025-05-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Notifications',
                'managed': False,
            },
        ),
    ]
